minimum_movement_delay = 0.35
unstuck_movement_delay = 6.0
unstuck_movement_hold_time = 3.0
perceived_tile_size = 75
wall_model_classes = [ "wall", "bush", "close_bush",]
gadget_pixels_minimum = 1300.0
hypercharge_pixels_minimum = 1800.0
super_pixels_minimum = 1800.0
idle_pixels_minimum = 75000.0
centered_wall_detection = false
wall_detection_confidence = 0.7
entity_detection_confidence = 0.5
seconds_to_hold_attack_after_reaching_max = 1.5
play_again_on_win = "yes"
current_playstyle = "yann-universal.iris"
max_losses = 1
max_consecutive_losses = 0
