cpu_or_gpu = "auto"
max_ips = 60
trophies_multiplier = 1
run_for_minutes = 0
emulator_port = 5555
api_base_url = "default"
brawl_stars_package = "com.supercell.brawlstars"
ocr_scale_down_factor = 0.6
used_threads = 4
player_tag = "#"
default_trophy_target = 500
auto_load_queue_on_startup = true
play_order = "lowest_to_highest"
alarm_enabled = true
