webhook_url = ""
discord_id = ""
ping_when_stuck = true
ping_when_target_is_reached = true
ping_every_x_match = 0
ping_every_x_minutes = 0
telegram_token = ""
telegram_chat_id = ""
discord_bot_token = ""
discord_guild_id = ""
